[package]
name = "app"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
console_error_panic_hook = "0.1.7"
log = "0.4.27"
pretty_env_logger = "0.5.0"
ranim.workspace = true
ranim-app.workspace = true
