[package]
name = "ranim-core"
description = "The core library of Ranim."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
# ranim-macros.workspace = true
approx = "0.5.1"
dyn-clone = "1.0.20"
inventory = "0.3.21"
tracing.workspace = true
itertools.workspace = true
glam = { workspace = true, features = ["approx", "bytemuck"] }
bytemuck = { workspace = true, features = ["derive"] }
derive_more = { workspace = true, features = [
  "deref_mut",
  "deref",
  "index",
  "index_mut",
  "is_variant",
  "as_ref",
  "from",
  "into_iterator",
] }
color = "0.3.2"
variadics_please = "1.1.0"

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen.workspace = true

[dev-dependencies]
assert_float_eq = "1.2.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.release]
tag = false
