[package]
name = "ranim-app"
description = "The preview application for Ranim."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
profiling = ["dep:puffin", "dep:puffin_http", "dep:profiling"]

[dependencies]
ranim = { workspace = true, default-features = false }
ranim-render.workspace = true
tracing.workspace = true
wgpu.workspace = true
bytemuck = { workspace = true, features = ["derive"] }
egui = "0.33.0"
async-channel = "2.5.0"
web-time = "1.1.0"
# profiling
puffin = { version = "0.19.1", optional = true }
puffin_http = { version = "0.16.1", optional = true }
profiling = { version = "1.0.17", optional = true, features = [
  "profile-with-puffin",
] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
eframe = { version = "0.33.0", features = ["wgpu"] }
pollster = "0.4.0"

[target.'cfg(target_family = "wasm")'.dependencies]
eframe = { version = "0.33.0", default-features = false, features = [
    "accesskit",
    "default_fonts",
    "web_screen_reader",
    "wgpu",
] }
wasm-bindgen.workspace = true
wasm-bindgen-futures = "0.4.54"
web-sys = "0.3.81"
console_error_panic_hook = "0.1.7"
wasm-tracing = "2.1.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.release]
tag = false
