# The URL the site will be built for
base_url = "https://azurice.github.io/ranim"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

author = "AzurIce"

[languages.zh]
# generate_feeds = true

[markdown.highlighting]
# When set to "true", missing highlight languages are treated as errors. Defaults to false but recommended to set to true.
error_on_missing_language = false

# Whether to use inline hex colours (`inline`) or CSS classes (`class`)
style = "class"

# If you use a single theme, put its name here. See the syntax highlighting  page for the possible choices.
theme = "catppuccin-mocha"

# If you want light/dark themes, use the 2 fields below instead. See the syntax highlighting  page for the possible choices.
light_theme = ""
dark_theme = ""

# A list of files for additional JSON TextMate grammars
extra_grammars = []

# A list of files for additional JSON TextMate themes
extra_themes = []

[extra]
# Put all your custom variables here
